architecture-beta
    group users(cloud)
    group edge(cloud)
    group api_security(cloud)
    group compute(cloud)
    group ai_ml(cloud)
    group data(cloud)
    group observability(cloud)
    group external(cloud)

    service farmers(server) in users

    service cloudfront(server) in edge
    service s3web(disk) in edge
    service s3audio(disk) in edge

    service apigw(server) in api_security
    service cognito(server) in api_security
    service secrets(database) in api_security

    service orchestrator(server) in compute
    service domainlambdas(server) in compute
    service profileotp(server) in compute

    service bedrock(server) in ai_ml
    service translate(server) in ai_ml
    service polly(server) in ai_ml

    service chatsessions(database) in data
    service farmerprofiles(database) in data
    service ratelimits(database) in data

    service cloudwatch(server) in observability
    service xray(server) in observability

    service openweather(server) in external

    farmers:R -- L:cloudfront
    cloudfront:R -- L:s3web
    cloudfront:B -- T:s3audio
    s3web:R -- L:apigw

    apigw:B -- T:cognito
    apigw:R -- L:orchestrator
    apigw:B -- T:profileotp
    apigw:R -- L:secrets

    orchestrator:B -- T:domainlambdas
    orchestrator:R -- L:bedrock
    orchestrator:R -- L:translate
    orchestrator:R -- L:polly

    orchestrator:B -- T:chatsessions
    orchestrator:B -- T:ratelimits
    profileotp:B -- T:farmerprofiles

    domainlambdas:R -- L:openweather

    apigw:B -- T:cloudwatch
    orchestrator:B -- T:cloudwatch
    domainlambdas:B -- T:cloudwatch
    orchestrator:B -- T:xray
