version: 0.2

env:
  variables:
    REGION: ap-south-1
    ACCOUNT_ID: "948809294205"
    S3_BUCKET: smart-rural-ai-948809294205
    S3_KEY: agentcore-code/SmartRuralAdvisor.zip
    RUNTIME_ID: SmartRuralAdvisor-lcQ47nFSPm
    ROLE_ARN: "arn:aws:iam::948809294205:role/smart-rural-ai-AgentCoreRuntimeRole"

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "=== Building AgentCore ARM64 package ==="
      - uname -m
      - python3 --version
      - pip3 install --upgrade pip

  build:
    commands:
      - echo "Installing agent dependencies..."
      - mkdir -p /tmp/agent_pkg

      # Install only bedrock-agentcore (minimal) for init test
      - pip3 install bedrock-agentcore -t /tmp/agent_pkg --quiet
      - echo "Deps installed, removing unnecessary packages..."

      # Remove boto3/botocore (pre-installed in runtime)
      - rm -rf /tmp/agent_pkg/botocore* /tmp/agent_pkg/boto3* /tmp/agent_pkg/s3transfer*
      - rm -rf /tmp/agent_pkg/dateutil* /tmp/agent_pkg/jmespath* /tmp/agent_pkg/urllib3*

      # Remove test/docs/cache dirs
      - find /tmp/agent_pkg -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - find /tmp/agent_pkg -type d -name tests -exec rm -rf {} + 2>/dev/null || true
      - find /tmp/agent_pkg -type d -name "*.dist-info" -exec rm -rf {} + 2>/dev/null || true

      # Remove .pyc .pyo
      - find /tmp/agent_pkg -name "*.pyc" -delete 2>/dev/null || true
      - find /tmp/agent_pkg -name "*.pyo" -delete 2>/dev/null || true

      # Create minimal agent.py (no strands, no tools - just echo)
      - |
        cat > /tmp/agent_pkg/agent.py << 'AGENT_EOF'
        import os, sys, json, logging, time
        _start = time.time()
        logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(name)s | %(message)s")
        logger = logging.getLogger("smart-rural-agent")
        logger.info(f"Module load start (Python {sys.version})")

        from bedrock_agentcore import BedrockAgentCoreApp
        logger.info(f"BedrockAgentCoreApp imported in {time.time()-_start:.1f}s")

        app = BedrockAgentCoreApp()
        logger.info(f"App created in {time.time()-_start:.1f}s")

        @app.entrypoint
        def invoke(payload: dict) -> dict:
            prompt = payload.get("prompt", "Hello!")
            logger.info(f"Invoke called: {prompt[:100]}")
            return {
                "result": f"Echo: {prompt}. I am the Smart Rural AI Advisor (minimal test mode).",
                "tools_used": [],
                "session_id": payload.get("session_id", "default"),
                "farmer_id": payload.get("farmer_id", "anon"),
            }

        if __name__ == "__main__":
            logger.info("Starting app...")
            app.run()
        AGENT_EOF
      - echo "=== agent.py content ==="
      - cat /tmp/agent_pkg/agent.py
      - echo ""

      # Show .so files to verify architecture
      - echo "=== Binary .so files (should be aarch64) ==="
      - find /tmp/agent_pkg -name "*.so" | head -20
      - file $(find /tmp/agent_pkg -name "*.so" | head -3) 2>/dev/null || echo "No .so files"

      # Show package size
      - du -sh /tmp/agent_pkg/
      - echo "=== Top-level dirs ==="
      - ls /tmp/agent_pkg/

      # Create zip
      - cd /tmp/agent_pkg && zip -r -q /tmp/SmartRuralAdvisor.zip . -x "*.pyc" "*.pyo"
      - ls -lh /tmp/SmartRuralAdvisor.zip
      - echo "Zip contents count:"
      - zipinfo -t /tmp/SmartRuralAdvisor.zip

  post_build:
    commands:
      - echo "Uploading zip to S3..."
      - aws s3 cp /tmp/SmartRuralAdvisor.zip s3://$S3_BUCKET/$S3_KEY
      - echo "Upload complete!"

      - echo "Updating AgentCore Runtime..."
      - |
        python3 -c "
        import boto3, json, time
        ac = boto3.client('bedrock-agentcore-control', region_name='$REGION')
        resp = ac.update_agent_runtime(
            agentRuntimeId='$RUNTIME_ID',
            agentRuntimeArtifact={
                'codeConfiguration': {
                    'code': {'s3': {'bucket': '$S3_BUCKET', 'prefix': '$S3_KEY'}},
                    'runtime': 'PYTHON_3_13',
                    'entryPoint': ['agent.py'],
                }
            },
            roleArn='$ROLE_ARN',
            networkConfiguration={'networkMode': 'PUBLIC'},
        )
        print(f'Update initiated: {resp.get(\"status\")}')

        # Wait for runtime to be ready
        for i in range(30):
            time.sleep(10)
            detail = ac.get_agent_runtime(agentRuntimeId='$RUNTIME_ID')
            status = detail.get('status', 'UNKNOWN')
            print(f'  [{(i+1)*10}s] {status}')
            if status in ('ACTIVE', 'READY'):
                print(f'Runtime is {status}!')
                break
            if 'FAILED' in (status or ''):
                reason = detail.get('failureReason', '?')
                print(f'FAILED: {reason}')
                exit(1)
        else:
            print('Timed out waiting for runtime')
            exit(1)
        "
      - echo "=== AgentCore ARM64 deployment complete ==="
