AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Rural AI Advisor - Serverless Backend

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.13
    Environment:
      Variables:
        BEDROCK_AGENT_ID: !Ref BedrockAgentId
        BEDROCK_AGENT_ALIAS_ID: !Ref BedrockAgentAliasId
        BEDROCK_KB_ID: !Ref BedrockKBId
        OPENWEATHER_API_KEY: !Ref OpenWeatherApiKey
        S3_KNOWLEDGE_BUCKET: !Sub 'smart-rural-ai-${AWS::AccountId}'
        DYNAMODB_PROFILES_TABLE: farmer_profiles
        DYNAMODB_SESSIONS_TABLE: chat_sessions
        AGENTCORE_RUNTIME_ARN: !Ref AgentCoreRuntimeArn

Parameters:
  BedrockAgentId:
    Type: String
    Description: Bedrock AgentCore Agent ID
    Default: PLACEHOLDER
  BedrockAgentAliasId:
    Type: String
    Description: Bedrock AgentCore Alias ID
    Default: PLACEHOLDER
  BedrockKBId:
    Type: String
    Description: Bedrock Knowledge Base ID
    Default: PLACEHOLDER
  OpenWeatherApiKey:
    Type: String
    Description: OpenWeatherMap API Key
    NoEcho: true
  AgentCoreRuntimeArn:
    Type: String
    Description: Amazon Bedrock AgentCore Runtime ARN (set after agentcore deploy)
    Default: ''

Resources:
  # S3 Bucket and DynamoDB tables created manually (already exist)
  # S3: smart-rural-ai-948809294205
  # DynamoDB: farmer_profiles, chat_sessions

  # Lambda Functions
  AgentOrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/agent_orchestrator/
      Handler: handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeAgent
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - bedrock-agentcore:InvokeAgentRuntime
              Resource: '*'
            - Effect: Allow
              Action:
                - translate:TranslateText
                - translate:DetectDominantLanguage
              Resource: '*'
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub 'arn:aws:s3:::smart-rural-ai-${AWS::AccountId}/*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/chat_sessions'
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/farmer_profiles'
      Events:
        ChatApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post
        ChatOptions:
          Type: Api
          Properties:
            Path: /chat
            Method: options
        VoiceApi:
          Type: Api
          Properties:
            Path: /voice
            Method: post
        VoiceOptions:
          Type: Api
          Properties:
            Path: /voice
            Method: options

  CropAdvisoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/crop_advisory/
      Handler: handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:RetrieveAndGenerate
                - bedrock:Retrieve
              Resource: '*'

  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/weather_lookup/
      Handler: handler.lambda_handler
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /weather/{location}
            Method: get
        WeatherOptions:
          Type: Api
          Properties:
            Path: /weather/{location}
            Method: options

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        def lambda_handler(event, context):
            return {
                'statusCode': 200,
                'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
                'body': '{"status": "healthy", "service": "Smart Rural AI Advisor"}'
            }
      Handler: index.lambda_handler
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

  ImageAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/image_analysis/
      Handler: handler.lambda_handler
      Timeout: 60
      MemorySize: 512
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: '*'
            - Effect: Allow
              Action:
                - translate:TranslateText
              Resource: '*'
      Events:
        ImageApi:
          Type: Api
          Properties:
            Path: /image-analyze
            Method: post
        ImageOptions:
          Type: Api
          Properties:
            Path: /image-analyze
            Method: options

  GovtSchemesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/govt_schemes/
      Handler: handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:RetrieveAndGenerate
                - bedrock:Retrieve
              Resource: '*'
      Events:
        SchemesApi:
          Type: Api
          Properties:
            Path: /schemes
            Method: get
        SchemesOptions:
          Type: Api
          Properties:
            Path: /schemes
            Method: options

  FarmerProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/farmer_profile/
      Handler: handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/farmer_profiles'
      Events:
        ProfileGetApi:
          Type: Api
          Properties:
            Path: /profile/{farmerId}
            Method: get
        ProfilePutApi:
          Type: Api
          Properties:
            Path: /profile/{farmerId}
            Method: put
        ProfileOptions:
          Type: Api
          Properties:
            Path: /profile/{farmerId}
            Method: options

  TranscribeSpeechFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas/transcribe_speech/
      Handler: handler.lambda_handler
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub 'arn:aws:s3:::smart-rural-ai-${AWS::AccountId}/*'
      Events:
        TranscribeApi:
          Type: Api
          Properties:
            Path: /transcribe
            Method: post
        TranscribeOptions:
          Type: Api
          Properties:
            Path: /transcribe
            Method: options

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
